version: "3.9"
services:
  fnano:
    container_name: fnano
    restart: always
    privileged: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      labels:
        - fnano
    volumes:
        - .:/code
    command:
      - /bin/sh
      - -c
      - |
        gunicorn app.main:app --workers 2 \
        --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:6969
    ports:
      - 6969:6969
  redis:
    container_name: redis
    restart: always
    image: redis:7.0.5-bullseye
    ports:
      - 6379:6379
  worker:
    container_name: celery-worker
    restart: always
    build: .
    command: celery -A app.celery worker --loglevel=INFO
    volumes:
      - .:/code
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    env_file:
      - .env 
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    privileged: true
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fnano

volumes:
  caddy_data:
    external: true
  caddy_config:
